<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-AHMVJTM" failures="1" tests="1" name="Default test" time="8.217" errors="0" timestamp="2025-03-19T21:26:17 IST">
  <testcase classname="ex_Selenium_DataDrivenTesting.DDT_RealTimeScenario" name="testDataDriven" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.nio.file.InvalidPathException: Illegal char &amp;lt;:&amp;gt; at index 33: E:\ABTB6x\LearningSeleniumATB6x\E:\ABTB6x\LearningSeleniumATB6x\resources\TataData.xlsx">
      <![CDATA[java.lang.RuntimeException: java.nio.file.InvalidPathException: Illegal char <:> at index 33: E:\ABTB6x\LearningSeleniumATB6x\E:\ABTB6x\LearningSeleniumATB6x\resources\TataData.xlsx
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)
at org.testng.internal.Parameters.handleParameters(Parameters.java:809)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 33: E:\ABTB6x\LearningSeleniumATB6x\E:\ABTB6x\LearningSeleniumATB6x\resources\TataData.xlsx
at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
at java.base/java.io.File.toPath(File.java:2401)
at org.apache.poi.openxml4j.opc.ZipPackage.openZipEntrySourceStream(ZipPackage.java:209)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:199)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:171)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:247)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:179)
at org.apache.poi.ooxml.POIXMLDocument.openPackage(POIXMLDocument.java:88)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:358)
at ex_Selenium_DataDrivenTesting.ExcelReader.getDataFromSheet(ExcelReader.java:139)
at ex_Selenium_DataDrivenTesting.DDT_RealTimeScenario.testDataExcel(DDT_RealTimeScenario.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)
... 25 more
]]>
    </failure>
  </testcase> <!-- testDataDriven -->
</testsuite> <!-- Default test -->
